version: "3.9"
services:
     asset:
       build: ./data-source-app
       ports:
         - "8500:8500"
       volumes:
         - ./data-source-app:/assetapp
       networks:
         - app_network
       environment:
         - NO_PROXY=localhost,127.0.0.1,server,client

     server:
       build: ./backend-flask
       ports:
         - "5000:5000"
       volumes:
         - ./backend-flask:/serverapp
       environment:
         - FLASK_ENV=development
         - NO_PROXY=localhost,127.0.0.1,asset,client
       depends_on:
         - asset
       networks:
         - app_network

     client:
       build: ./react-front-end
       ports:
         - "3000:3000"
       volumes:
         - ./react-front-end:/clientapp
       depends_on:
         - server
       networks:
         - app_network
       environment:
         - NO_PROXY=localhost,127.0.0.1,server,asset

networks:
     app_network:
       driver: bridge
